# Generated by Django 5.0.2 on 2025-03-23 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fees", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feetransaction",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
    ]
