# Generated by Django 5.0.2 on 2025-03-23 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fees", "0002_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentdiscount",
            name="approved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentdiscount",
            name="discount",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fees.discount"
            ),
        ),
        migrations.AddField(
            model_name="studentdiscount",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="feestructure",
            unique_together={("category", "class_name", "academic_year")},
        ),
        migrations.AlterUniqueTogether(
            name="studentdiscount",
            unique_together={("student", "discount")},
        ),
    ]
