# Generated by Django 5.0.2 on 2025-03-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("layout", models.JSONField(default=dict)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dashboards",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("admission", "Admission Report"),
                            ("academic", "Academic Report"),
                            ("attendance", "Attendance Report"),
                            ("financial", "Financial Report"),
                            ("expense", "Expense Report"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("excel", "Excel")], max_length=10
                    ),
                ),
                ("parameters", models.JSONField(default=dict)),
                ("file", models.FileField(upload_to="reports/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "db_table": "reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recipients", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("last_sent", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "scheduled_reports",
            },
        ),
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("chart", "Chart"),
                            ("table", "Table"),
                            ("metric", "Metric"),
                        ],
                        max_length=20,
                    ),
                ),
                ("configuration", models.JSONField(default=dict)),
                ("position", models.JSONField(default=dict)),
                ("refresh_interval", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "widgets",
                "ordering": ["dashboard", "position"],
            },
        ),
    ]
